Repository iden3/go-iden3-core, pull requests merged in 2019-01, with the labels that each got.

#47 Move EthBytes functions to utils
  core/claim.go
  services/claimsrv/claimproofs.go
  services/claimsrv/service.go
  utils/utils.go
Labels: enhancement

#49 Feature/adminsrv
  cmd/relay/commands/server.go
  cmd/relay/config/load.go
  cmd/relay/endpoint/admin.go
  cmd/relay/endpoint/serve.go
  db/admin.go
  db/leveldb.go
  db/memory.go
  db/storage.go
  services/adminsrv/service.go
Labels: buidl

#53 Sync claims to spec and update tests
  core/claim.go
  core/claim_test.go
  merkletree/merkletree.go
  merkletree/node.go
Labels: bug, buidl

#55 Fix NewProofFromBytes for proof with aux node, add tests
  merkletree/merkletree.go
  merkletree/merkletree_test.go
Labels: bug

#56 Fix merkletree and claim new versions to compile again and pass the t…
  cmd/relay/commands/claim.go
  cmd/relay/config/load.go
  cmd/relay/endpoint/admin.go
  cmd/relay/endpoint/claim.go
  cmd/relay/endpoint/name.go
  cmd/relay/endpoint/relay.go
  cmd/relay/endpoint/serve.go
  core/claim.go
  core/claim_test.go
  db/leveldb.go
  merkletree/merkletree.go
  merkletree/merkletree_test.go
  merkletree/node.go
  merkletreeDoc/example.go
  services/adminsrv/service.go
  services/claimsrv/claimproofs.go
  services/claimsrv/messages.go
  services/claimsrv/service.go
  services/claimsrv/service_test.go
  services/identitysrv/service.go
  services/namesrv/service.go
Labels: bug, buidl

#57 Add error when adding an MT entry with already existing index
  merkletree/merkletree.go
  merkletree/merkletree_test.go
Labels: bug

#58 Update documentation
  core/claim.go
  merkletree/merkletree.go
  merkletree/node.go
Labels: enhancement

#59 small update adding proof of claim in nameresolver, and added utils/signature tests
  cmd/relay/endpoint/name.go
  cmd/relay/endpoint/serve.go
  utils/signatures_test.go
Labels: buidl

#62 update mimc7 to last circomlib version
  crypto/mimc7/mimc7.go
  crypto/mimc7/mimc7_test.go
Labels: buidl

#63 Update claims to latest spec
  core/claim.go
  core/claim_test.go
Labels: buidl

#64 Update test vectors for latest mimc7
  core/claim_test.go
  merkletree/merkletree_test.go
  merkletree/utils_test.go
  services/claimsrv/claimproofs.go
  services/claimsrv/service_test.go
  services/identitysrv/service.go
Labels: buidl

#65 Integration/mimc7update
  core/claim.go
  core/claim_test.go
  crypto/mimc7/mimc7.go
  crypto/mimc7/mimc7_test.go
  merkletree/merkletree_test.go
  merkletree/utils_test.go
  services/claimsrv/claimproofs.go
  services/claimsrv/service_test.go
  services/identitysrv/service.go
Labels: buidl

#66 mimc7 update, compatible with iden3js and circomlib mimc7 implementation
  crypto/mimc7/mimc7.go
  crypto/mimc7/mimc7_test.go
Labels: buidl

#67 Feature/claimauthksignp256
  core/claim.go
  core/claim_test.go
  merkletree/merkletree_test.go
  merkletree/utils_test.go
  services/claimsrv/service_test.go
Labels: buidl

#68 Integration/mimc7update
  core/claim.go
  core/claim_test.go
  crypto/mimc7/mimc7.go
  crypto/mimc7/mimc7_test.go
  merkletree/merkletree_test.go
  merkletree/utils_test.go
  services/claimsrv/service_test.go
Labels: buidl

#69 Feature/registerid
  Relay.md
  cmd/backupserver/endpoint/serve.go
  cmd/centrauth/endpoint/serve.go
  cmd/id/endpoint/rest.go
  cmd/id/endpoint/rest_test.go
  cmd/relay/endpoint/claim.go
  cmd/relay/endpoint/id.go
  cmd/relay/endpoint/name.go
  cmd/relay/endpoint/relay_test.go
  cmd/relay/endpoint/serve.go
  core/claim.go
  core/claim_test.go
  merkletree/merkletree_test.go
  services/adminsrv/service.go
  services/backupsrv/messages.go
  services/backupsrv/service.go
  services/centrauthsrv/messages.go
  services/claimsrv/claimproofs.go
  services/claimsrv/messages.go
  services/claimsrv/service.go
  services/claimsrv/service_test.go
  services/identitysrv/service.go
  services/namesrv/messages.go
  services/namesrv/service.go
  services/namesrv/service_test.go
Labels: buidl

#71 Feature/proofofclaimapi
  cmd/relay/endpoint/admin.go
  cmd/relay/endpoint/claim.go
  cmd/relay/endpoint/id.go
  cmd/relay/endpoint/name.go
  common/common.go
  merkletree/merkletree.go
  merkletree/merkletree_test.go
  merkletree/utils.go
  services/adminsrv/service.go
  services/backupsrv/service.go
  services/centrauthsrv/service.go
  services/claimsrv/claimproofs.go
  services/claimsrv/messages.go
  services/claimsrv/service.go
  services/claimsrv/service_test.go
  services/identitysrv/service.go
  services/signsrv/service.go
  utils/signatures.go
  utils/utils.go
Labels: buidl

#73 Feature/proofofclaimapi
  cmd/backupserver/endpoint/rest.go
  cmd/backupserver/endpoint/serve.go
  cmd/centrauth/endpoint/rest.go
  cmd/centrauth/endpoint/serve.go
  cmd/relay/endpoint/claim.go
  cmd/relay/endpoint/id.go
  core/proof.go
  merkletree/merkletree.go
  services/adminsrv/service.go
  services/backupsrv/messages.go
  services/backupsrv/service.go
  services/centrauthsrv/messages.go
  services/centrauthsrv/service.go
  services/claimsrv/claimproofs.go
  services/claimsrv/messages.go
  services/claimsrv/service.go
  services/identitysrv/service.go
  services/namesrv/messages.go
  services/signsrv/service.go
  utils/signatures.go
  utils/utils.go
Labels: buidl

#74 proof data structs with lower cammelCase (aka dromedaryCase)
  core/proof.go
Labels: buidl

#81 Add mt.Walk tree iterator, used by mt.GraphViz and mt.DumpClaims
  merkletree/merkletree.go
  merkletree/merkletree_test.go
Labels: buidl

#80 Add graphviz example
  README.md
  merkletreeDoc/.gitignore
  merkletreeDoc/example.go
  merkletreeDoc/merkletree.md
  merkletreeDoc/merkletree_graphviz.png
Labels: enhancement
